# Generated by Django 4.1.5 on 2023-01-17 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flammemanager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
            ],
        ),
    ]
