# Generated by Django 4.1.5 on 2023-01-18 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flammemanager', '0005_remove_livraison_produit_livraison_id_livraison'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chantier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_chantier', models.CharField(max_length=100, unique=True)),
                ('etat', models.CharField(choices=[('en attente', 'en attente'), ('planifié', 'planifié'), ('validé', 'validé'), ('terminé', 'terminé')], max_length=20)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flammemanager.client')),
                ('livraisons', models.ManyToManyField(to='flammemanager.livraison')),
            ],
        ),
    ]
