# Generated by Django 4.1.5 on 2023-01-18 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flammemanager', '0008_remove_commande_prix_ttc_commande_prix_achat_ht_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livraison',
            name='commande',
        ),
        migrations.AddField(
            model_name='livraison',
            name='commande',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='flammemanager.commande'),
            preserve_default=False,
        ),
    ]
