# Generated by Django 4.1.5 on 2023-01-18 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flammemanager', '0010_client_id_client'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='id_client',
            new_name='client_id',
        ),
    ]
