# Generated by Django 4.1.5 on 2023-01-18 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flammemanager', '0012_rename_client_id_client_id_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livraison',
            name='client',
        ),
        migrations.AddField(
            model_name='livraison',
            name='client',
            field=models.ManyToManyField(to='flammemanager.client'),
        ),
    ]
