# Generated by Django 4.1.5 on 2023-01-18 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flammemanager', '0013_remove_livraison_client_livraison_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livraison',
            name='client',
        ),
    ]
