# Generated by Django 4.1.5 on 2023-01-18 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flammemanager', '0014_remove_livraison_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chantier',
            name='livraisons',
        ),
        migrations.AddField(
            model_name='chantier',
            name='livraisons',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='flammemanager.commande'),
            preserve_default=False,
        ),
    ]
