# Generated by Django 4.1.5 on 2023-01-18 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flammemanager', '0018_remove_chantier_livraisons_chantier_livraisons'),
    ]

    operations = [
        migrations.AddField(
            model_name='chantier',
            name='client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='flammemanager.client'),
            preserve_default=False,
        ),
    ]
