# Generated by Django 4.1.5 on 2023-01-18 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flammemanager', '0022_livraison_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chantier',
            name='etat_chantier',
            field=models.CharField(choices=[('en attente', 'En attente'), ('planifié', 'Planifié'), ('validé', 'Validé'), ('terminé', 'Terminé')], max_length=20),
        ),
        migrations.AlterField(
            model_name='commande',
            name='etat_commande',
            field=models.CharField(choices=[('en attente', 'En attente'), ('terminé', 'Terminé')], max_length=20),
        ),
    ]
