# Generated by Django 4.1.5 on 2023-01-19 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flammemanager', '0023_alter_chantier_etat_chantier_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livraison',
            name='etat_livraison',
            field=models.CharField(choices=[('commandé', 'Commandé'), ('livré', 'Livré'), ('complet', 'Complet')], max_length=20),
        ),
    ]
