# Generated by Django 4.1.5 on 2023-01-19 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flammemanager', '0024_alter_livraison_etat_livraison'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='num_devis',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
