# Generated by Django 4.1.5 on 2023-01-20 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flammemanager', '0030_produit_fournisseur'),
    ]

    operations = [
        migrations.CreateModel(
            name='Solde',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etat_solde', models.CharField(choices=[('en attente', 'En attente'), ('partiel', 'Partiel'), ('soldé', 'Soldé')], max_length=20)),
                ('id_facture', models.CharField(max_length=20)),
                ('chantier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flammemanager.chantier')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flammemanager.client')),
            ],
        ),
    ]
