# Generated by Django 4.1.5 on 2023-01-20 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flammemanager', '0035_alter_solde_date_solde'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='num_devis',
        ),
        migrations.AddField(
            model_name='commande',
            name='num_devis',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='chantier',
            name='type_chantier',
            field=models.CharField(choices=[('intervention légère', 'Intervention légère'), ('intervention classique', 'Intervention classique')], max_length=22),
        ),
    ]
