# Generated by Django 4.1.5 on 2023-01-20 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flammemanager', '0040_alter_chantier_nombre_de_jours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='prix_achat_ht',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
