# Generated by Django 4.1.5 on 2023-01-20 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flammemanager', '0041_alter_commande_prix_achat_ht'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='commentaire',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
