# Generated by Django 4.1.5 on 2023-01-20 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flammemanager', '0044_remove_chantier_commande_chantier_commentaire'),
    ]

    operations = [
        migrations.AddField(
            model_name='chantier',
            name='chantier_commencé',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='chantier',
            name='commentaire',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='commande',
            name='commentaire',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
