# Generated by Django 4.1.5 on 2023-01-20 22:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flammemanager', '0045_chantier_chantier_commencé_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chantier',
            name='date_intervention',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
    ]
