# Generated by Django 4.1.5 on 2023-01-20 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flammemanager', '0046_alter_chantier_date_intervention'),
    ]

    operations = [
        migrations.AddField(
            model_name='solde',
            name='prix_facture_ht',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
