# Generated by Django 4.1.5 on 2023-02-04 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flammemanager', '0049_remove_livraison_produits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solde',
            name='commande',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='flammemanager.commande'),
        ),
    ]
