# Generated by Django 4.1.9 on 2023-06-25 17:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flammemanager', '0052_echeancier'),
    ]

    operations = [
        migrations.RenameField(
            model_name='propositioncommerciale',
            old_name='date_envoi',
            new_name='date_devis',
        ),
        migrations.RenameField(
            model_name='propositioncommerciale',
            old_name='type_proposition',
            new_name='marque',
        ),
        migrations.RenameField(
            model_name='propositioncommerciale',
            old_name='montant_ttc',
            new_name='montant_ht',
        ),
        migrations.AddField(
            model_name='propositioncommerciale',
            name='date_entree',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='propositioncommerciale',
            name='type_devis',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
