# Generated by Django 4.1.5 on 2023-01-17 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flammemanager', '0002_produit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_commande', models.CharField(max_length=100, unique=True)),
                ('prix_ttc', models.DecimalField(decimal_places=2, max_digits=5)),
                ('commande', models.BooleanField(default=False)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flammemanager.client')),
                ('produits', models.ManyToManyField(to='flammemanager.produit')),
            ],
        ),
    ]
