# Generated by Django 4.1.5 on 2023-01-17 21:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flammemanager', '0003_commande'),
    ]

    operations = [
        migrations.CreateModel(
            name='Livraison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etat_livraison', models.CharField(choices=[('commandé', 'Commandé'), ('en livraison', 'En Livraison'), ('livré', 'Livré'), ('complet', 'Complet')], default='commandé', max_length=20)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flammemanager.client')),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flammemanager.commande')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flammemanager.produit')),
            ],
        ),
    ]
