# Generated by Django 4.1.5 on 2023-01-18 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flammemanager', '0004_livraison'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livraison',
            name='produit',
        ),
        migrations.AddField(
            model_name='livraison',
            name='id_livraison',
            field=models.CharField(default=1, max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
