# Generated by Django 4.1.5 on 2023-01-18 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flammemanager', '0006_chantier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livraison',
            name='commande',
        ),
        migrations.AddField(
            model_name='livraison',
            name='commande',
            field=models.ManyToManyField(to='flammemanager.commande'),
        ),
    ]
