# Generated by Django 4.1.5 on 2023-01-18 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flammemanager', '0007_remove_livraison_commande_livraison_commande'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commande',
            name='prix_ttc',
        ),
        migrations.AddField(
            model_name='commande',
            name='prix_achat_ht',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='commande',
            name='prix_vente_ht',
            field=models.DecimalField(decimal_places=2, default=2, max_digits=10),
            preserve_default=False,
        ),
    ]
