# Generated by Django 4.1.5 on 2023-01-18 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flammemanager', '0009_remove_livraison_commande_livraison_commande'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='id_client',
            field=models.CharField(default=1, max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
