# Generated by Django 4.1.5 on 2023-01-18 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flammemanager', '0011_rename_id_client_client_client_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='client_id',
            new_name='id_client',
        ),
    ]
