# Generated by Django 4.1.5 on 2023-01-18 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flammemanager', '0015_remove_chantier_livraisons_chantier_livraisons'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chantier',
            name='livraisons',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flammemanager.livraison'),
        ),
    ]
