# Generated by Django 4.1.5 on 2023-01-18 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flammemanager', '0016_alter_chantier_livraisons'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chantier',
            name='client',
        ),
    ]
