# Generated by Django 4.1.5 on 2023-01-18 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flammemanager', '0017_remove_chantier_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chantier',
            name='livraisons',
        ),
        migrations.AddField(
            model_name='chantier',
            name='livraisons',
            field=models.ManyToManyField(to='flammemanager.livraison'),
        ),
    ]
