# Generated by Django 4.1.5 on 2023-01-18 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flammemanager', '0019_chantier_client'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chantier',
            old_name='etat',
            new_name='etat_chantier',
        ),
        migrations.RemoveField(
            model_name='commande',
            name='commande',
        ),
        migrations.AddField(
            model_name='commande',
            name='etat_commande',
            field=models.CharField(choices=[('en attente', 'en attente'), ('terminé', 'terminé')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='livraison',
            name='etat_livraison',
            field=models.CharField(choices=[('commandé', 'Commandé'), ('en livraison', 'En Livraison'), ('livré', 'Livré'), ('complet', 'Complet')], max_length=20),
        ),
    ]
