# Generated by Django 4.1.5 on 2023-01-18 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flammemanager', '0020_rename_etat_chantier_etat_chantier_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chantier',
            name='id_chantier',
        ),
        migrations.RemoveField(
            model_name='client',
            name='id_client',
        ),
        migrations.RemoveField(
            model_name='commande',
            name='id_commande',
        ),
        migrations.RemoveField(
            model_name='livraison',
            name='id_livraison',
        ),
    ]
