# Generated by Django 4.1.5 on 2023-01-18 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flammemanager', '0021_remove_chantier_id_chantier_remove_client_id_client_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='livraison',
            name='client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='flammemanager.client'),
            preserve_default=False,
        ),
    ]
