# Generated by Django 4.1.5 on 2023-01-19 17:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flammemanager', '0025_client_num_devis'),
    ]

    operations = [
        migrations.AddField(
            model_name='livraison',
            name='date_reelle',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
