# Generated by Django 4.1.5 on 2023-01-19 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flammemanager', '0026_livraison_date_reelle'),
    ]

    operations = [
        migrations.AddField(
            model_name='chantier',
            name='nombre_de_jours',
            field=models.DecimalField(decimal_places=1, default=1, max_digits=3),
            preserve_default=False,
        ),
    ]
