# Generated by Django 4.1.5 on 2023-01-19 17:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flammemanager', '0027_chantier_nombre_de_jours'),
    ]

    operations = [
        migrations.AddField(
            model_name='chantier',
            name='date_intervention',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
