# Generated by Django 4.1.5 on 2023-01-19 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flammemanager', '0028_chantier_date_intervention'),
    ]

    operations = [
        migrations.AddField(
            model_name='chantier',
            name='type_chantier',
            field=models.CharField(choices=[('chantier commencé', 'Chantier commencé'), ('intervention classique', 'Intervention classique')], default='chantier commencé', max_length=22),
            preserve_default=False,
        ),
    ]
