# Generated by Django 4.1.5 on 2023-01-19 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flammemanager', '0029_chantier_type_chantier'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='fournisseur',
            field=models.CharField(default='test', max_length=200),
            preserve_default=False,
        ),
    ]
