# Generated by Django 4.1.5 on 2023-01-20 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flammemanager', '0032_alter_solde_id_facture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solde',
            name='id_facture',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
