# Generated by Django 4.1.5 on 2023-01-20 17:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flammemanager', '0033_alter_solde_id_facture'),
    ]

    operations = [
        migrations.AddField(
            model_name='solde',
            name='date_solde',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
