# Generated by Django 4.1.5 on 2023-01-20 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flammemanager', '0034_solde_date_solde'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solde',
            name='date_solde',
            field=models.DateField(blank=True, null=True),
        ),
    ]
