# Generated by Django 4.1.5 on 2023-01-20 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flammemanager', '0036_remove_client_num_devis_commande_num_devis_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solde',
            name='commande',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='flammemanager.commande'),
            preserve_default=False,
        ),
    ]
