# Generated by Django 4.1.5 on 2023-01-20 19:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flammemanager', '0037_solde_commande'),
    ]

    operations = [
        migrations.RenameField(
            model_name='livraison',
            old_name='date_reelle',
            new_name='date_livraison',
        ),
        migrations.AddField(
            model_name='commande',
            name='date_commande',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
