# Generated by Django 4.1.5 on 2023-01-20 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flammemanager', '0038_rename_date_reelle_livraison_date_livraison_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commande',
            old_name='date_commande',
            new_name='date_entree',
        ),
        migrations.RenameField(
            model_name='livraison',
            old_name='date_livraison',
            new_name='date_commande',
        ),
    ]
