# Generated by Django 4.1.5 on 2023-01-20 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flammemanager', '0039_rename_date_commande_commande_date_entree_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chantier',
            name='nombre_de_jours',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
    ]
