# Generated by Django 4.1.5 on 2023-01-20 21:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flammemanager', '0042_commande_commentaire'),
    ]

    operations = [
        migrations.AddField(
            model_name='chantier',
            name='commande',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='flammemanager.commande'),
            preserve_default=False,
        ),
    ]
