# Generated by Django 4.1.5 on 2023-01-20 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flammemanager', '0043_chantier_commande'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chantier',
            name='commande',
        ),
        migrations.AddField(
            model_name='chantier',
            name='commentaire',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
