# Generated by Django 4.1.5 on 2023-01-28 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flammemanager', '0047_solde_prix_facture_ht'),
    ]

    operations = [
        migrations.AddField(
            model_name='livraison',
            name='produits',
            field=models.ManyToManyField(to='flammemanager.produit'),
        ),
    ]
