# Generated by Django 4.1.5 on 2023-01-28 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flammemanager', '0048_livraison_produits'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livraison',
            name='produits',
        ),
    ]
