# Generated by Django 4.1.9 on 2023-06-24 14:20

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flammemanager', '0050_alter_solde_commande'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropositionCommerciale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_envoi', models.DateField(default=datetime.date.today)),
                ('numero_devis', models.CharField(max_length=20)),
                ('type_proposition', models.CharField(max_length=100)),
                ('montant_ttc', models.DecimalField(decimal_places=2, max_digits=10)),
                ('statut', models.CharField(choices=[('envoye', 'Envoyé'), ('rappel', 'Rappelé'), ('attente', 'En attente'), ('auaide', 'Au aide'), ('valide', 'Validé'), ('perdu', 'Perdu')], max_length=20)),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flammemanager.client')),
            ],
        ),
    ]
