# Generated by Django 4.1.9 on 2023-06-24 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flammemanager', '0051_propositioncommerciale'),
    ]

    operations = [
        migrations.CreateModel(
            name='Echeancier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_echeance', models.DateField()),
                ('montant_total_ttc', models.DecimalField(decimal_places=2, max_digits=10)),
                ('montant_paye', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('statut', models.CharField(choices=[('en attente', 'En attente'), ('partiellement payé', 'Partiellement payé'), ('payé', 'Payé'), ('en retard', 'En retard'), ('annulé', 'Annulé')], max_length=20)),
                ('commentaire', models.TextField(blank=True)),
                ('facture_associee', models.FileField(blank=True, upload_to='factures/')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flammemanager.client')),
            ],
        ),
    ]
