# Generated by Django 4.1.9 on 2023-06-25 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flammemanager', '0053_rename_date_envoi_propositioncommerciale_date_devis_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='echeancier',
            name='facture_associee',
        ),
        migrations.AddField(
            model_name='echeancier',
            name='date_facture',
            field=models.DateField(default='1999-01-01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='echeancier',
            name='type_paiement',
            field=models.CharField(choices=[('virement', 'Virement'), ('prelevement', 'Virement')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
